#!/usr/bin/env sh
# Regenerate every tool-native agent file. Two sources of truth, rendered out — never hand-duplicated:
#   * the universal preamble  = the MIRROR block in AGENTS.md (read-order + non-negotiables + guardrails)
#   * the rule bodies         = the full text of every .agents/rules/*.md module
# Single-file mirrors render the rule INDEX (module → one-line description → path), NOT the bodies:
# inlining every body made a ~184KB file that a harness caps and reads as a silent prefix — neither
# small nor complete while claiming both. Per-rule `.mdc` files keep each rule's FULL body verbatim,
# scoped by the rule's own `Applies when:` line. AGENTS.md is refilled in place too, between its
# <!-- PANOPLY:RULES:BEGIN/END --> markers. Never hand-edit a mirror or the AGENTS.md rules block;
# edit AGENTS.md (preamble) or .agents/rules/*.md (bodies) and re-run. POSIX sh, no runtime deps —
# Git Bash, WSL, macOS, Linux, CI.
#   sh scripts/sync-agents.sh              # write mirrors + refill AGENTS.md rules index block
#   sh scripts/sync-agents.sh --check      # exit 1 if any mirror / the AGENTS.md block is stale (CI gate)
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/AGENTS.md"
RULES_DIR="$ROOT/.agents/rules"
[ -f "$SRC" ] || { echo "AGENTS.md not found; run /adapt-agents-setup first." >&2; exit 1; }
[ -d "$RULES_DIR" ] || { echo ".agents/rules/ not found." >&2; exit 1; }

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# --- The rule modules, in read order. Curated order first (clean-architecture is the premise every
#     other module inherits from), then any other .agents/rules/*.md not listed, so a newly added module
#     is never silently dropped. Missing modules (pruned by /adapt) are skipped. ---
ORDER="algorithm clean-architecture workflow quality-bar git-workflow documentation code-style testing error-handling database data-modeling api-design frontend design-system ai-features agent-readiness"
MODULES=""
for m in $ORDER; do
  [ -f "$RULES_DIR/$m.md" ] && MODULES="$MODULES $m"
done
for f in "$RULES_DIR"/*.md; do
  [ -f "$f" ] || continue
  b="$(basename "$f" .md)"
  case " $MODULES " in *" $b "*) ;; *) MODULES="$MODULES $b" ;; esac
done
[ -n "$MODULES" ] || { echo "No rule modules under .agents/rules/." >&2; exit 1; }

# The universal preamble body: the MIRROR block extracted from AGENTS.md (single source of truth).
MIRROR="$(awk '/MIRROR:start/{f=1;next} /MIRROR:end/{f=0} f' "$SRC")"
[ -n "$MIRROR" ] || { echo "No MIRROR block found in AGENTS.md." >&2; exit 1; }

GEN="<!-- GENERATED by scripts/sync-agents.sh from AGENTS.md + .agents/rules/*.md — DO NOT EDIT. Edit AGENTS.md (preamble) or .agents/rules/*.md (rule bodies) and re-run \`sh scripts/sync-agents.sh\`. -->"
NOTE="> **This file is an INDEX, not the ruleset.** It carries the universal preamble, then names every
> \`.agents/rules/\` module with a one-line description and the path to read.
>
> Where the full rule text lives depends on the FORMAT, and the two are deliberate:
>
> - **Single-file mirrors (this file)** carry the index only. They are read whole by a tool that also
>   has file access, so a named path it can open is not a pointer into nowhere — and inlining every
>   body made a ~184KB file that harnesses **silently truncated** at their cap, so it was neither
>   small nor complete while claiming to be both. \`AGENTS.md\` was already an index for this reason;
>   these files now match it.
> - **Per-rule modules** (\`.cursor/rules/*.mdc\`, \`.agents/rules/*.mdc\`) carry each rule's FULL body
>   verbatim, one rule per file, scoped by the rule's own \`Applies when:\` condition. A tool that loads
>   only one file, or cannot follow a path, gets the complete text of every rule that applies to it.
>
> Rule bodies are canonical under \`.agents/rules/*.md\` — one home, no second copy to drift.
>
> It is generated; do not edit it. Edit \`AGENTS.md\` (the preamble) or \`.agents/rules/*.md\` (the rule
> bodies) and run \`sh scripts/sync-agents.sh\`."

TMP="$(mktemp)"
RULESTMP="$(mktemp)"
INDEXTMP="$(mktemp)"
trap 'rm -f "$TMP" "$RULESTMP" "$INDEXTMP"' EXIT INT TERM

# Concatenate every rule module's full body, separated by an hr. This full rendering is the input to
# the `.mdc` modules (one rule per file); it is NOT inlined into the single-file mirrors.
render_rules() {
  _first=1
  for m in $MODULES; do
    if [ "$_first" -eq 1 ]; then _first=0; else printf '\n---\n\n'; fi
    cat "$RULES_DIR/$m.md"
  done
}
render_rules > "$RULESTMP"

# One-line description of a rule module: its `# ` H1, else its filename. Used by the INDEX.
rule_desc() { # $1 = module basename
  _d="$(sed -n 's/^# //p' "$RULES_DIR/$1.md" | head -1)"
  [ -n "$_d" ] || _d="$1"
  printf '%s' "$_d"
}

# Single-file mirrors render an INDEX, not the rule bodies. This is deliberate: those files are read
# whole by a harness, and inlining the full corpus made every one a ~184KB read (~47,000 tokens) that
# a cap then silently truncated — neither self-contained nor honest, while contradicting the kit's
# "one fact, one home" doctrine by shipping every rule body a second time. The index names each
# module, its one-line description, and the path to read; bodies stay canonical under .agents/rules/.
render_index() {
  for m in $MODULES; do
    # Backticks here are MARKDOWN code spans, not command substitution. shellcheck cannot tell, so
    # SC2016 is disabled on this line rather than escaped: the literal backticks are the point.
    # shellcheck disable=SC2016
    printf -- '- `%s` — %s — `.agents/rules/%s.md`\n' "$m" "$(rule_desc "$m")" "$m"
  done
}
render_index > "$INDEXTMP"

STALE=0
# Compare TMP against the on-disk target (check mode) or install it (write mode).
# In CHECK mode, a target that does not exist on disk is SKIPPED, not flagged stale: every tool-native
# mirror is gitignored (the canonical source is .agents/ + AGENTS.md), so in CI none of them exist and
# there is nothing to compare. The only committed generated artifact is AGENTS.md's rules block, which
# is checked explicitly below. Locally, generated-but-drifted mirrors are still caught.
put() { # $1 = repo-relative path
  dst="$ROOT/$1"
  if [ "$CHECK" -eq 1 ]; then
    [ -f "$dst" ] || return 0
    if ! diff -q "$TMP" "$dst" >/dev/null 2>&1; then
      echo "STALE: $1"; STALE=1
    fi
  else
    mkdir -p "$(dirname "$dst")"
    cp "$TMP" "$dst"
    echo "wrote $1"
  fi
}

# A mirror = frontmatter (optional) + preamble + the rules INDEX (not the rule bodies).
#
# The bodies are deliberately NOT inlined. Inlining every module produced a ~184KB file per tool —
# ~47,000 tokens read at session start by any tool that loads it — while being silently truncated by
# harnesses that cap the file, so it neither fit nor was actually complete. `AGENTS.md` was already
# converted to an index for this reason (see render_index above); the mirrors were left behind and are
# now consistent with it. One fact, one home: the bodies stay canonical under `.agents/rules/*.md`.
build_mirror() { # $1 = optional frontmatter
  {
    [ -n "${1:-}" ] && printf '%s\n' "$1"
    printf '%s\n\n' "$GEN"
    printf '%s\n\n' "$NOTE"
    printf '%s\n\n' "$MIRROR"
    printf '%s\n\n' "---"
    printf '## Rules modules — read the ones this task touches\n\n'
    render_index
  } > "$TMP"
}

# --- Concatenated, single-file mirrors (preamble + rules INDEX) ---
build_mirror ""                        ; put ".github/copilot-instructions.md"
build_mirror ""                        ; put "GEMINI.md"
build_mirror ""                        ; put "CONVENTIONS.md"
build_mirror ""                        ; put ".clinerules/00-agents.md"
build_mirror "---
trigger: always_on
---"                                    ; put ".windsurf/rules/00-agents.md"

# --- Cursor: one .mdc per rule module, plus a preamble file.
#
# `alwaysApply: true` on EVERY module meant a Cursor session force-loaded the whole corpus (~47,000
# tokens) no matter the task — the same defect the old concatenated CLAUDE.md had, reached a different
# way. Modules whose own header says "Applies when: always" keep `alwaysApply: true`; the conditional
# ones (api-design, database, frontend, ai-features, ...) are emitted with `alwaysApply: false` and a
# description carrying their activation condition, so the tool loads them only when the work matches.
# The condition is read from the module itself — not restated here, which is how the two would drift. ---
build_cursor_preamble() {
  {
    printf '%s\n' "---"
    printf 'description: %s\n' "Panoply — universal preamble & read-order (all rule modules load alongside this)"
    printf 'alwaysApply: true\n'
    printf '%s\n\n' "---"
    printf '%s\n\n' "$GEN"
    printf '%s\n\n' "$NOTE"
    printf '%s\n' "$MIRROR"
  } > "$TMP"
}
build_cursor_module() { # $1 = module basename
  title="$(sed -n 's/^# //p' "$RULES_DIR/$1.md" | head -1)"
  [ -n "$title" ] || title="$1"
  # The module's OWN declared activation condition decides alwaysApply. Reading it here rather than
  # keeping a second list in this script is the point: a hand-maintained list drifts from the rule.
  cond="$(sed -n 's/.*Applies when:[ ]*//p' "$RULES_DIR/$1.md" | head -1 | sed 's/\*\*//g; s/^[*> ]*//; s/[ ]*$//')"
  case "$cond" in
    always*|ALWAYS*) always="true"  ; when="always" ;;
    "")              always="true"  ; when="always (no condition declared)" ;;
    *)               always="false" ; when="$cond" ;;
  esac
  {
    printf '%s\n' "---"
    if [ "$always" = "true" ]; then
      printf 'description: %s\n' "Panoply rule — $title (read 00-preamble.mdc first for the read-order)"
    else
      printf 'description: %s\n' "Panoply rule — $title. Applies when: $when"
    fi
    printf 'alwaysApply: %s\n' "$always"
    printf '%s\n\n' "---"
    printf '%s\n\n' "$GEN"
    cat "$RULES_DIR/$1.md"
  } > "$TMP"
}
build_cursor_preamble ; put ".cursor/rules/00-preamble.mdc"
for m in $MODULES; do
  build_cursor_module "$m" ; put ".cursor/rules/$m.mdc"
done

# Prune the agent .mdc files we previously generated whose module no longer exists (e.g. pruned by /adapt,
# or the old single 00-agents.mdc layout). Only touch files bearing our GENERATED marker.
DESIRED="00-preamble"
for m in $MODULES; do DESIRED="$DESIRED $m"; done
if [ -d "$ROOT/.cursor/rules" ]; then
  for f in "$ROOT"/.cursor/rules/*.mdc; do
    [ -f "$f" ] || continue
    b="$(basename "$f" .mdc)"
    case " $DESIRED " in *" $b "*) continue ;; esac
    grep -q 'GENERATED by scripts/sync-agents.sh' "$f" 2>/dev/null || continue
    if [ "$CHECK" -eq 1 ]; then
      echo "STALE (orphan): .cursor/rules/$b.mdc"; STALE=1
    else
      rm -f "$f"; echo "removed orphan .cursor/rules/$b.mdc"
    fi
  done
fi

# --- the agent hub: AGENTS.md root file + generated mirror files. These are gitignored in the kit so
#     the canonical source stays agent-agnostic, but we generate them locally for tools that read them.
#
#     NEVER write into .agents/rules/ here — that is the canonical SOURCE, not a mirror. (An earlier
#     version of this script did exactly that: it wrapped each canonical module in Cursor `.mdc`
#     frontmatter and wrote it back over the source, corrupting all 16 rule modules. The source is
#     read-only to this script; mirrors are generated FROM it, one direction only.) ---
build_mirror ""                        ; put "CLAUDE.md"
for m in $MODULES; do
  build_cursor_module "$m" ; put ".agents/rules/$m.mdc"
done

# Prune .agents/rules/ orphans (generated .mdc files whose module no longer exists).
# Only touch files bearing our GENERATED marker; canonical .md files are sacred.
DESIRED_MDC=""
for m in $MODULES; do DESIRED_MDC="$DESIRED_MDC $m"; done
if [ -d "$ROOT/.agents/rules" ]; then
  for f in "$ROOT"/.agents/rules/*.mdc; do
    [ -f "$f" ] || continue
    b="$(basename "$f" .mdc)"
    case " $DESIRED_MDC " in *" $b "*) continue ;; esac
    grep -q 'GENERATED by scripts/sync-agents.sh' "$f" 2>/dev/null || continue
    if [ "$CHECK" -eq 1 ]; then
      echo "STALE (orphan): .agents/rules/$b.mdc"; STALE=1
    else
      rm -f "$f"; echo "removed orphan .agents/rules/$b.mdc"
    fi
  done
fi

# --- AGENTS.md: refill the rule INDEX between the PANOPLY:RULES markers, preserving all hand-authored
#     content outside the block. The full bodies are NOT inlined here (see render_index above): the
#     canonical text lives once under .agents/rules/*.md, and this block points at it. ---
if ! grep -q 'PANOPLY:RULES:BEGIN' "$SRC" || ! grep -q 'PANOPLY:RULES:END' "$SRC"; then
  echo "AGENTS.md is missing the <!-- PANOPLY:RULES:BEGIN/END --> markers." >&2
  exit 1
fi
awk -v rules="$INDEXTMP" '
  /PANOPLY:RULES:BEGIN/ { print; print ""; while ((getline line < rules) > 0) print line; print ""; skip=1; next }
  /PANOPLY:RULES:END/   { skip=0; print; next }
  skip { next }
  { print }
' "$SRC" > "$TMP"
if [ "$CHECK" -eq 1 ]; then
  if ! diff -q "$TMP" "$SRC" >/dev/null 2>&1; then echo "STALE: AGENTS.md (rules index block)"; STALE=1; fi
else
  cp "$TMP" "$SRC"; echo "refilled AGENTS.md rules index block"
fi

if [ "$CHECK" -eq 1 ]; then
  [ "$STALE" -eq 0 ] && { echo "Mirrors + AGENTS.md in sync with the preamble and rule modules."; exit 0; }
  echo "Mirrors are stale — run: sh scripts/sync-agents.sh" >&2; exit 1
fi
echo "Mirrors regenerated from AGENTS.md + .agents/rules/*.md (single-file mirrors carry the index; .mdc modules carry the bodies)."
